
sudo: required
dist: trusty

language: ruby
rvm:
  - 2.2.4

services:
  - postgresql

before_install:
  - sudo apt-get -qq update
  - sudo apt-get -y install libpq-dev

install:
  - bundle install
  - rake db:setup