- artigas
- canelones
- cerro largo
- colonia
- durazno
- flores
- florida
- lavalleja
- maldonado
- montevideo
- paysandú
- rivera
- rocha
- río negro
- salto
- san josé
- soriano
- tacuarembó
- treinta y tres